/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface CustomBallotInterface extends ethers.utils.Interface {
  functions: {
    "proposals(uint256)": FunctionFragment;
    "referenceBlock()": FunctionFragment;
    "spentVotePower(address)": FunctionFragment;
    "vote(uint256,uint256)": FunctionFragment;
    "voteToken()": FunctionFragment;
    "votingPower()": FunctionFragment;
    "winnerName()": FunctionFragment;
    "winningProposal()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "referenceBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "spentVotePower",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "voteToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "votingPower",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "winnerName",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "winningProposal",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "referenceBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "spentVotePower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "voteToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "winnerName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "winningProposal",
    data: BytesLike
  ): Result;

  events: {
    "Voted(address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Voted"): EventFragment;
}

export type VotedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber] & {
    voter: string;
    proposal: BigNumber;
    weight: BigNumber;
    proposalVotes: BigNumber;
  }
>;

export class CustomBallot extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: CustomBallotInterface;

  functions: {
    proposals(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { name: string; voteCount: BigNumber }>;

    referenceBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    spentVotePower(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    vote(
      proposal: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    voteToken(overrides?: CallOverrides): Promise<[string]>;

    votingPower(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { votingPower_: BigNumber }>;

    winnerName(
      overrides?: CallOverrides
    ): Promise<[string] & { winnerName_: string }>;

    winningProposal(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { winningProposal_: BigNumber }>;
  };

  proposals(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { name: string; voteCount: BigNumber }>;

  referenceBlock(overrides?: CallOverrides): Promise<BigNumber>;

  spentVotePower(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  vote(
    proposal: BigNumberish,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  voteToken(overrides?: CallOverrides): Promise<string>;

  votingPower(overrides?: CallOverrides): Promise<BigNumber>;

  winnerName(overrides?: CallOverrides): Promise<string>;

  winningProposal(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    proposals(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { name: string; voteCount: BigNumber }>;

    referenceBlock(overrides?: CallOverrides): Promise<BigNumber>;

    spentVotePower(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    vote(
      proposal: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    voteToken(overrides?: CallOverrides): Promise<string>;

    votingPower(overrides?: CallOverrides): Promise<BigNumber>;

    winnerName(overrides?: CallOverrides): Promise<string>;

    winningProposal(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "Voted(address,uint256,uint256,uint256)"(
      voter?: string | null,
      proposal?: BigNumberish | null,
      weight?: null,
      proposalVotes?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber],
      {
        voter: string;
        proposal: BigNumber;
        weight: BigNumber;
        proposalVotes: BigNumber;
      }
    >;

    Voted(
      voter?: string | null,
      proposal?: BigNumberish | null,
      weight?: null,
      proposalVotes?: null
    ): TypedEventFilter<
      [string, BigNumber, BigNumber, BigNumber],
      {
        voter: string;
        proposal: BigNumber;
        weight: BigNumber;
        proposalVotes: BigNumber;
      }
    >;
  };

  estimateGas: {
    proposals(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    referenceBlock(overrides?: CallOverrides): Promise<BigNumber>;

    spentVotePower(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    vote(
      proposal: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    voteToken(overrides?: CallOverrides): Promise<BigNumber>;

    votingPower(overrides?: CallOverrides): Promise<BigNumber>;

    winnerName(overrides?: CallOverrides): Promise<BigNumber>;

    winningProposal(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    proposals(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    referenceBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    spentVotePower(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vote(
      proposal: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    voteToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    votingPower(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    winnerName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    winningProposal(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
