/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CustomBallot } from "./CustomBallot";

export { CustomBallot__factory } from "./factories/CustomBallot__factory";
